modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "silentsean"
description = "Safely authenticate Minecraft accounts in development environments."
logoFile = "assets/devsession/logo.png"

[[mixins]]
config = "mixins.devsession.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "devauth"
type = "incompatible"
ordering = "AFTER"
side = "BOTH"
