modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "DJtheRedstoner"
description = "Safely authenticate Minecraft accounts in development environments."
logoFile = "assets/devauth/logo.png"

[[mixins]]
config = "mixins.devauth.json"

[[dependencies.devauth]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
